name: First Workflow
on:
  workflow_dispatch:
jobs:
  Job1:
    runs-on: ubuntu-latest
    name: job 1
    steps:
       - run: |
           echo "step 1"
           echo "step 2"

  Job2:
    runs-on: ubuntu-latest
    name: job 2
    steps:
    - name: Ship it
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'ship ship ship!'
        color: 'red'
